---
#this will be the yaml file for the mass deployment playbook
#the command used to execute this will look like
#ansible-playbook mass_dep.yml -e "dest_path=/dest/path/example target=webservers source_path=/source/path/example"   
#l command tnjm tkoun ghalta ama bch ysir deployment li naarfou li lezm ykoun fama target, source, w dest, ken nalka hajet neksin f thneya tw nzidhom


#playbook def
- name: mass deployment
  hosts: "{{ target | default('all') }}"
  serial: "{{ serial | default('100%') }}"
  become: yes
#basically li f wost l hosts howa variable keeen l target specified fl command, bch ystaamlou, sinon by default yemchi b all
#serial hedhi haja yeser mezyena, ken nhottlou ena serial=3 fl command, yabda b 3 machines, ykmlhom, baed ytaada l 3 okhrin
#yaani bch in case ykounou aandi barcha vms bch naaml fehom deployment (weli howa l cas li ena fih) ma ytbloukech LOL


  pre_tasks:
  #pretasks hatitha just to ensure li hedhi tt3ada kbal l actual deployment tasks
    - name: checking the variables
      assert:
        that:
          - dest_path is defined
          - source_path is defined
        fail_msg: "Missing variables, make sure these variables are correct: dest_path, target, source_path"
        success_msg: "all good, proceeding to the deployment"
#assert returns a boolean after checking if the variables are defined or not
# "that" is used to give the list of variables to check 
#fail_msg is the output of a failure in one of the paths
#i wont check the target cz its already defaulted to all, i made the mistake of checking it XD

  tasks:
    - name: check if the source file actually exists
      local_action:
        module: stat
        path: "{{ source_path }}"
      register: reg_source_check
      run_once: true

#tbh im not convinced bl register ama i dont know how to send a fail message from the stat module, so im seperating them into two tasks for now
#i used the register to use the output of the stat in the next task

    - name: fail message
        assert:
          that:
            - reg_source_check.stat.exists
        fail_msg: "the source path you used ('{{ source_path}}') doesnt exist on your machine"
#wait no, i am convinced by the register now, im a genius XDD
#behi, the stat returns a dictionary with alot of values, khamem feha ka liste fl python 
#feha value esmha exists, hedhi feha true ken l path mawjoud, w false if not
#if it s false, assert returns the fail message

#doing the same thing for the dest path
    - name: check if destination file actually exists
        module: stat
        path: "{{ dest_path }}"
        register: reg_dest_check

    - name: creating the path if it doesnt exist 
        msg: "dest path doesnt exist on '{{ ansible_user }}' , creating"
        ansible.builtin.command: mkdir "{{ dest_path }}"
        msg: "dest path created"
        when: reg_dest_check.stat.exists == true

