---
- name: version control and deployment
  hosts: all
  become: no


  vars:
    rollback: false
  pre_tasks:
    - name: getting the actual number of versions
      ansible.builtin.command: ls -v /home/kali/Desktop/ansible/testls/front/
      register: num_ver
      delegate_to: localhost

    - name: correspondance of latest
      ansible.builtin.shell: ls -v  /home/kali/Desktop/ansible/testls/front/ | tail -n 1
      register: latest
      delegate_to: localhost

  vars_prompt:
    - name: source_input
      prompt: "What's the source dir: 1-Back 2-Front"
      private: no

    - name: dest_dir
      prompt: "What's the dest_dir (please dont leave it blank if u r keeping .ssh or any important files in ~)"
      private: no

#    - name: version
#      prompt: "What's the version you are uploading: {{ num_ver.stdout_lines }}, or choose latest "
#      private: no

    - name: num_copy
      prompt: "what's the number of copies you want"
      private: no

  tasks:

    - name: ask version
      ansible.builtin.pause:
        prompt: "What's the version you are uploading: {{ num_ver.stdout_lines }}, or choose latest "
      register: version_input
      when: version is not defined

    - set_fact:
        version: "{{ latest.stdout if version_input.user_input == 'latest' else version_input.user_input }}"
      when: version is not defined

    - set_fact:
        source_dir: "{{ 'back' if source_input == '1' else 'front' }}"

########################################################################
#i used a task called ask version because ansible runs in this order
# 1-vars
# 2-vars_prompt
# 3-pretasks
# 4-tasks
#so using the variables generated from the pretasks in the pretasks in the vars_prompt isnt even possibnle cz it runs before the pretasks
#so here using the pause module i can enter the version i want and save it in a variable named version_input
#and then the set fact will set the version for me with conditions on the latest
#######################################################################

#using this for testing cz i keep getting an error abt the source not existing while it does
    - name: verifying the source path
      ansible.builtin.stat:
        path: "/home/kali/Desktop/ansible/testls/{{ source_dir }}/{{ version }}/"
      register: source_check
      delegate_to: localhost

    - name: outputting if the file exists or not
      ansible.builtin.debug:
        msg: "file path exits"
      when: source_check.stat.exists

    - name: removing old version
      ansible.builtin.file:
        path: "/home/ubuntu/{{ dest_dir }}/{{ source_dir }}/"
        state: absent
      # idk this is what i could find best suited for my use XDD

    - name: deploying new version
      ansible.builtin.copy:
        src: "/home/kali/Desktop/ansible/testls/{{ source_dir }}/{{ version }}/"
        dest: "/home/ubuntu/{{ dest_dir }}/{{ source_dir }}/{{ version }}copy_{{ item }}/"
        owner: ubuntu
        group: ubuntu
        mode: "0644"
      loop: "{{ range(1, (num_copy | int) + 1) | list }}"

    - name: Show deployment completion message
      ansible.builtin.debug:
        msg: "DEPLOYMENT COMPLETED SUCCESSFULLY"

    # hedhi optional ama habit naaml deployment verification, so there it is
    - name: Verify deployment
      ansible.builtin.stat:
        path: "/home/ubuntu/{{ dest_dir }}"
      register: deployed_dir

    - name: Confirm deployment success
      ansible.builtin.debug:
        msg: "Files deployed to /home/ubuntu/{{ dest_dir }}/ , now saving it in the {{ source_dir }}_commit"
      when: deployed_dir.stat.exists

    - name: Append new deployment record to _commit file
      ansible.builtin.lineinfile:
        path: "/home/ubuntu/{{ dest_dir }}/{{ source_dir }}_commit"
        line: "version | {{ version }} | copies | {{ num_copy }} | {{ ansible_date_time.date }} :: {{ ansible_date_time.time }} | rollback | {{ rollback }}"


...
