---
- name: version control and deployment
  hosts: all
  become: no

  vars_prompt:
    - name: source_dir
      prompt: "What's the source dir"
      private: no

    - name: dest_dir
      prompt: "What's the dest_dir (needs to be like [folder_name/], please dont leave it blank if u r keeping .ssh or any important files in ~)"
      private: no

    - name: version
      prompt: "What's the version you are uploading"
      private: no

    - name: num_copy
      prompt: "what's the number of copies you want"
      private: no

  tasks:

#using this for testing cz i keep getting an error abt the source not existing while it does
    - name: verifying the source path
      ansible.builtin.stat:
        path: "{{ source_dir }}/{{ version }}/"
      register: source_check
      delegate_to: localhost

    - name: outputting if the file exists or not
      ansible.builtin.debug:
        msg: "file path exits"
      when: source_check.stat.exists

    - name: removing old version
      ansible.builtin.file:
        path: "/home/ubuntu/{{ dest_dir }}"
        state: absent
      # idk this is what i could find best suited for my use XDD

    - name: deploying new version
      ansible.builtin.copy:
        src: "{{ source_dir }}/{{ version }}/"
        dest: "/home/ubuntu/{{ dest_dir }}/{{ version }}copy_{{ item }}/"
        owner: ubuntu
        group: ubuntu
        mode: "0644"
      loop: "{{ range(1, (num_copy | int) + 1) | list }}"

    - name: Show deployment completion message
      ansible.builtin.debug:
        msg: "DEPLOYMENT COMPLETED SUCCESSFULLY"

    # hedhi optional ama habit naaml deployment verification, so there it is
    - name: Verify deployment
      ansible.builtin.stat:
        path: "/home/ubuntu/{{ dest_dir }}"
      register: deployed_dir

    - name: Confirm deployment success
      ansible.builtin.debug:
        msg: "Files deployed to /home/ubuntu/{{ dest_dir }}/"
      when: deployed_dir.stat.exists

...
