
---
- name: version control and deployment
  hosts: all
  become: false


  vars:
    rollback: false
  vars_prompt:
    - name: source_input
      prompt: "What's the source dir: 1-rt 2-path"
      private: no

    - name: num_copy
      prompt: "what's the number of copies you want"
      private: no


  tasks:
    - set_fact:
        source_dir: "{{ 'rt' if source_input == '1' else 'path' }}"
        trigger_type: "{{ 'real_time' if source_input == '1' else 'path_' }}"

    - name: getting the versions
      ansible.builtin.command: ls -v ~/collectors/{{ source_dir }}/
      register: num_ver
      delegate_to: localhost
      run_once: true

    - name: correspondance of latest
      ansible.builtin.shell: ls -v  ~/collectors/{{ source_dir }}/ | tail -n 1
      register: latest
      delegate_to: localhost
      run_once: true

    - name: ask version
      ansible.builtin.pause:
        prompt: "What's the version you are uploading: {{ num_ver.stdout_lines }}, or choose latest "
      register: version_input
      run_once: true
      delegate_to: localhost

    - name: Set GLOBAL version
      set_fact:
        version: "{{ latest.stdout if version_input.user_input == 'latest' else version_input.user_input }}"
      run_once: true


#---------------------- source path check -----------------
    - name: verifying the source path
      ansible.builtin.stat:
        path: "~/collectors/{{ source_dir }}/{{ version }}/"
      register: source_check
      delegate_to: localhost
      failed_when: not source_check.stat.exists

#--------------------------removing old .jar ----------------------------
    - name: find old jar files in collector directories
      ansible.builtin.find:
        paths: "~/collectors/{{ source_dir }}_{{ item }}/"
        patterns: "*.jar"
      loop: "{{  range(1, (num_copy | int) + 1) | list  }}"
      register: found_jars

    - name: remove old jar files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ found_jars.results | map(attribute='files') | flatten }}"

#-------------------------deployment-------------------
    - name: finding the actual .jar file
      ansible.builtin.find:
        paths: "~/collectors/{{ source_dir }}/{{ version }}/"
        patterns: "*.jar"
        file_type: file
      register: deployment_jar
      delegate_to: localhost
      run_once: true


    - name: deploying new version
      ansible.builtin.copy:
        src: "{{ deployment_jar.files[0].path }}"
        dest: "~/collectors/{{ source_dir }}_{{ item }}/"
        mode: "0644"
      loop: "{{ range(1, (num_copy | int) + 1) | list }}"

#-----------------------trigger-------------------------
    - name: running the new .jar files using the shell script
      ansible.builtin.shell: sh /etc/init.d/{{ trigger_type }}_collector.sh restart
      become: true

    - name: checking the processes
      ansible.builtin.shell: ps aux | grep jar | grep {{ source_dir }}
      register: processes
      become: true
      failed_when: not processes.stdout_lines | length == num_copy + 1 | int

#-----------------------updating commit-----------------
    - name: Append new deployment record to _commit file
      ansible.builtin.lineinfile:
        path: "~/collectors/{{ trigger_type }}_commit"
        line: "version | {{ version }} | copies | {{ num_copy }} | {{ ansible_date_time.date }} :: {{ ansible_date_time.time }} | rollback | {{ rollback }}"

    - name: verifying the existence of the commit files in the local host
      ansible.builtin.stat:
        path: "~/collectors/{{ trigger_type }}_commit"
      register: commit_check
      delegate_to: localhost

    - name: creating the commit if it doesnt exist
      ansible.builtin.shell: touch ~/collectors/{{ source_dir }}_commit
      delegate_to: localhost
      when: not commit_check.stat.exists

    - name: append new deployment in _commit file in local host
      ansible.builtin.lineinfile:
        path: "~/collectors/{{ trigger_type }}_commit"
        line: "host | {{ ansible_default_ipv4.address }} | {{ ansible_date_time.date }} :: {{ ansible_date_time.time }} | version | {{ version }} | copies | {{ num_copy }} | rollback | {{ rollback }}"
      delegate_to: localhost
      when: commit_check.stat.exists



...
