---
- name: version control and deployment
  hosts: all
  become: no


  vars:
    rollback: false
  vars_prompt:
    - name: source_input
      prompt: "What's the source dir: 1-rt 2-path"
      private: no

#    - name: dest_dir
 #     prompt: "What's the dest_dir (please dont leave it blank if u r keeping .ssh or any important files in ~)"
  #    private: no

    - name: num_copy
      prompt: "what's the number of copies you want"
      private: no


  tasks:
    - set_fact:
        source_dir: "{{ 'rt' if source_input == '1' else 'path' }}"

    - name: getting the versions
      ansible.builtin.command: ls -v ~/collectors/{{ source_dir }}/
      register: num_ver
      delegate_to: localhost
      run_once: true

    - name: correspondance of latest
      ansible.builtin.shell: ls -v  ~/collectors/{{ source_dir }}/ | tail -n 1
      register: latest
      delegate_to: localhost
      run_once: true

    - name: ask version
      ansible.builtin.pause:
        prompt: "What's the version you are uploading: {{ num_ver.stdout_lines }}, or choose latest "
      register: version_input
      run_once: true
      delegate_to: localhost

    - name: Set GLOBAL version
      set_fact:
        version: "{{ latest.stdout if version_input.user_input == 'latest' else version_input.user_input }}"
      run_once: true


########################################################################
#i used a task called ask version because ansible runs in this order
# 1-vars
# 2-vars_prompt
# 3-pretasks
# 4-tasks
#so using the variables generated from the pretasks in the pretasks in the vars_prompt isnt even possibnle cz it runs before the pretasks
#so here using the pause module i can enter the version i want and save it in a variable named version_input
#and then the set fact will set the version for me with conditions on the latest
#######################################################################

#using this for testing cz i keep getting an error abt the source not existing while it does

#---------------------- source path check -----------------
    - name: verifying the source path
      ansible.builtin.stat:
        path: "~/collectors/{{ source_dir }}/{{ version }}/"
      register: source_check
      delegate_to: localhost

    - name: outputting if the file exists or not
      ansible.builtin.debug:
        msg: "file path exits"
      when: source_check.stat.exists

#--------------------------removing old .jar ----------------------------
    - name: find old jar files in collector directories
      ansible.builtin.find:
        paths: "~/collectors/{{ source_dir }}_{{ item }}/"
        patterns: "*.jar"
      loop: "{{  range(1, (num_copy | int) + 1) | list  }}"
      register: found_jars

    - name: remove old jar files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ found_jars.results | map(attribute='files') | flatten }}"

#-------------------------deployment-------------------
    - name: finding the actual .jar file
      ansible.builtin.find:
        paths: "~/collectors/{{ source_dir }}/{{ version }}/"
        patterns: "*.jar"
        file_type: file
      register: deployment_jar
      delegate_to: localhost
      run_once: true


    - name: deploying new version
      ansible.builtin.copy:
        src: "{{ deployment_jar.files[0].path }}"
        dest: "~/collectors/{{ source_dir }}_{{ item }}/"
        owner: ubuntu
        group: ubuntu
        mode: "0644"
      loop: "{{ range(1, (num_copy | int) + 1) | list }}"

    - name: Show deployment completion message
      ansible.builtin.debug:
        msg: "DEPLOYMENT COMPLETED SUCCESSFULLY"

#-----------------------updating commit-----------------
    - name: Append new deployment record to _commit file
      ansible.builtin.lineinfile:
        path: "~/collectors/{{ source_dir }}_commit"
        line: "version | {{ version }} | copies | {{ num_copy }} | {{ ansible_date_time.date }} :: {{ ansible_date_time.time }} | rollback | {{ rollback }}"

...
